
apiVersion: apps/v1
kind: Deployment
metadata:
  name: std20-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: std20-nginx-web
  template:
    metadata:
      labels:
        app: std20-nginx-web
    spec:
      containers:
      - name: std20-nginx-container
        image: smile1101/nginx:520ad24d6fc1a396544b3f50bba3b1757d6ad8bf
        ports:
          - containerPort: 80
--- 


apiVersion: v1
kind: Service
metadata:
  name: std20-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: std20-nginx-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---