
apiVersion: apps/v1
kind: Deployment
metadata:
  name: std20-nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: std20-nginx-web
  template:
    metadata:
      labels:
        app: std20-nginx-web
    spec:
      containers:
      - name: std20-nginx-container
        image: smile1101/nginx:952015a9a3575ed7802a72c3eea92ab2ce1dacfc
        ports:
          - containerPort: 80
--- 


apiVersion: v1
kind: Service
metadata:
  name: std20-nginx-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: std20-nginx-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---